# Generated by Django 5.0 on 2023-12-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='value',
            field=models.FloatField(),
        ),
    ]
