# Generated by Django 5.0 on 2023-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfinance', '0002_alter_compras_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('value_all', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
