# Generated by Django 5.0 on 2023-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfinance', '0006_compras_user_month_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='payment_number',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
