# Generated by Django 5.0 on 2023-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfinance', '0008_alter_month_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='value_all',
            field=models.FloatField(default=0),
        ),
    ]
