# Generated by Django 5.0 on 2023-12-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfinance', '0010_alter_month_value_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='modal_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
